import type { Env, Record as TdgRecord } from '../../lib/types'
import { json, jsonError } from '../../lib/http'

interface UpdateBody {
  date?: string
  counterparty?: string
  description?: string | null
  amount?: number
  gst_status?: 'free' | 'amount'
  gst_amount?: number
  category?: string | null
  reference?: string | null
  paid?: boolean
}

// Fields that can legitimately be cleared to null (description, category,
// reference) need "was this key sent at all" checks, not just `?? null` —
// otherwise a partial update (e.g. just toggling `paid`) would silently
// wipe them, since an omitted key and an explicit null look the same once
// bound as a SQL parameter.
export const onRequestPut: PagesFunction<Env> = async ({ request, env, params }) => {
  const id = params.id as string
  const existing = await env.DB.prepare('SELECT * FROM records WHERE id = ?').bind(id).first<TdgRecord>()
  if (!existing) return jsonError(404, 'Record not found')

  let body: UpdateBody
  try {
    body = await request.json()
  } catch {
    return jsonError(400, 'Invalid request body')
  }

  if (body.gst_status && body.gst_status !== 'free' && body.gst_status !== 'amount') {
    return jsonError(400, 'gst_status must be "free" or "amount"')
  }

  const has = (key: keyof UpdateBody) => Object.prototype.hasOwnProperty.call(body, key)

  await env.DB.prepare(
    `UPDATE records SET
      date = ?,
      counterparty = ?,
      description = ?,
      amount = ?,
      gst_status = ?,
      gst_amount = ?,
      category = ?,
      reference = ?,
      paid = ?,
      updated_at = ?
     WHERE id = ?`,
  )
    .bind(
      body.date ?? existing.date,
      body.counterparty ?? existing.counterparty,
      has('description') ? body.description : existing.description,
      body.amount ?? existing.amount,
      body.gst_status ?? existing.gst_status,
      body.gst_amount ?? existing.gst_amount,
      has('category') ? body.category : existing.category,
      has('reference') ? body.reference : existing.reference,
      body.paid === undefined ? existing.paid : body.paid ? 1 : 0,
      new Date().toISOString(),
      id,
    )
    .run()

  const record = await env.DB.prepare('SELECT * FROM records WHERE id = ?').bind(id).first()
  return json({ record })
}

export const onRequestDelete: PagesFunction<Env> = async ({ env, params }) => {
  const id = params.id as string
  const existing = await env.DB.prepare('SELECT file_key FROM records WHERE id = ?').bind(id).first<{
    file_key: string | null
  }>()
  if (!existing) return jsonError(404, 'Record not found')

  if (existing.file_key) {
    await env.FILES.delete(existing.file_key)
  }
  // Records generated by the invoice builder have a linked `invoices` row
  // (invoices.record_id -> records.id) — delete it first or the FK
  // constraint blocks deleting the record itself.
  await env.DB.prepare('DELETE FROM invoices WHERE record_id = ?').bind(id).run()
  await env.DB.prepare('DELETE FROM records WHERE id = ?').bind(id).run()

  return json({ ok: true })
}
