import type { Env, Record as TdgRecord } from '../../lib/types'
import { json, jsonError } from '../../lib/http'

interface UpdateBody {
  date?: string
  counterparty?: string
  description?: string | null
  amount?: number
  gst_status?: 'free' | 'amount'
  gst_amount?: number
  category?: string | null
  reference?: string | null
  paid?: boolean
  original_currency?: string | null
  original_amount?: number | null
  fx_rate?: number | null
  fx_rate_date?: string | null
}

// Fields that can legitimately be cleared to null (description, category,
// reference) need "was this key sent at all" checks, not just `?? null` —
// otherwise a partial update (e.g. just toggling `paid`) would silently
// wipe them, since an omitted key and an explicit null look the same once
// bound as a SQL parameter.
export const onRequestPut: PagesFunction<Env> = async ({ request, env, params }) => {
  const id = params.id as string
  const existing = await env.DB.prepare('SELECT * FROM records WHERE id = ?').bind(id).first<TdgRecord>()
  if (!existing) return jsonError(404, 'Record not found')

  let body: UpdateBody
  try {
    body = await request.json()
  } catch {
    return jsonError(400, 'Invalid request body')
  }

  if (body.gst_status && body.gst_status !== 'free' && body.gst_status !== 'amount') {
    return jsonError(400, 'gst_status must be "free" or "amount"')
  }

  const has = (key: keyof UpdateBody) => Object.prototype.hasOwnProperty.call(body, key)

  const amount = body.amount ?? existing.amount
  // The "Paid" switch is a blunt override — it's independent of the
  // itemized payments log (see /api/records/:id/payments), which is the
  // precise way to record partial payments. Flipping it snaps amount_paid
  // to 0 or the full amount; it isn't meant to be mixed with logging
  // individual payments against the same record.
  const amountPaid = has('paid') ? (body.paid ? amount : 0) : existing.amount_paid
  const paid = amountPaid >= amount ? 1 : 0

  // Foreign-currency audit trail: an explicit "AUD" (or empty) currency
  // clears the other fx fields rather than leaving stale original_amount/
  // fx_rate values behind from a previous edit.
  const currencyRaw = has('original_currency') ? body.original_currency : existing.original_currency
  const isForeign = !!currencyRaw && currencyRaw.toUpperCase() !== 'AUD'
  const originalCurrency = isForeign ? currencyRaw!.toUpperCase() : null
  const originalAmount = isForeign ? (has('original_amount') ? body.original_amount : existing.original_amount) : null
  const fxRate = isForeign ? (has('fx_rate') ? body.fx_rate : existing.fx_rate) : null
  const fxRateDate = isForeign ? (has('fx_rate_date') ? body.fx_rate_date : existing.fx_rate_date) : null

  await env.DB.prepare(
    `UPDATE records SET
      date = ?,
      counterparty = ?,
      description = ?,
      amount = ?,
      gst_status = ?,
      gst_amount = ?,
      category = ?,
      reference = ?,
      paid = ?,
      amount_paid = ?,
      original_currency = ?,
      original_amount = ?,
      fx_rate = ?,
      fx_rate_date = ?,
      updated_at = ?
     WHERE id = ?`,
  )
    .bind(
      body.date ?? existing.date,
      body.counterparty ?? existing.counterparty,
      has('description') ? body.description : existing.description,
      amount,
      body.gst_status ?? existing.gst_status,
      body.gst_amount ?? existing.gst_amount,
      has('category') ? body.category : existing.category,
      has('reference') ? body.reference : existing.reference,
      paid,
      amountPaid,
      originalCurrency,
      originalAmount,
      fxRate,
      fxRateDate,
      new Date().toISOString(),
      id,
    )
    .run()

  const record = await env.DB.prepare('SELECT * FROM records WHERE id = ?').bind(id).first()
  return json({ record })
}

export const onRequestDelete: PagesFunction<Env> = async ({ env, params }) => {
  const id = params.id as string
  const existing = await env.DB.prepare('SELECT file_key FROM records WHERE id = ?').bind(id).first<{
    file_key: string | null
  }>()
  if (!existing) return jsonError(404, 'Record not found')

  if (existing.file_key) {
    await env.FILES.delete(existing.file_key)
  }
  // Records generated by the invoice builder have a linked `invoices` row,
  // and income records may have logged `payments` rows — both reference
  // records(id), so delete them first or the FK constraint blocks deleting
  // the record itself.
  await env.DB.prepare('DELETE FROM invoices WHERE record_id = ?').bind(id).run()
  await env.DB.prepare('DELETE FROM payments WHERE record_id = ?').bind(id).run()
  await env.DB.prepare('DELETE FROM records WHERE id = ?').bind(id).run()

  return json({ ok: true })
}
